// dev/src/lib/Resume.svelte
<script>
    import Navbar from './Navbar.svelte';
</script>
  
<Navbar />

<div class="flex flex-col items-center px-5">
    <h1 class=" text-4xl py-8">Resume</h1>
    <iframe class="flex-grow w-full h-screen" title="Mohammed Mowla's Resume" src="https://drive.google.com/file/d/1ZIzCmbyars0g0Mb-Fw8J25N01T-txlOR/preview" allow="autoplay"></iframe>
</div>

// app/resume/page.tsx
'use client'

import { Navbar } from '../../components/Navbar';
import FadeInText from '@/components/FadeInText';

export default function ResumeContent() {
    return (
        <div>
            <main className="flex flex-col items-center">
                <FadeInText text="Resume" className='pt-16' additative={true}/>
                <iframe title="Mohammed Mowla's Resume" className="min-w-full min-h-screen md:px-24 md:py-16 py-12" src="https://drive.google.com/file/d/1LRT8oyhgvS-UE3zIvmz-OCEe5cCtdu9D/preview" allow="autoplay"></iframe>
            </main>

        </div>
    );
}
